"https://{default}/":
  type: upstream
  upstream: "frontend:http" 
  cache:
    enabled: false      

"https://{default}/api":
  type: upstream
  upstream: "backend:http" 
  cache:
    enabled: false 
